CC=gcc
CFLAGS=-std=gnu99 -Wall -fsanitize=address,undefined
LDFLAGS=-fsanitize=address,undefined
LDLIBS=-lpthread -lm

zad1: zad1.c
	$(CC) $(CFLAGS) -o zad1 zad1.c $(LDLIBS)

zad2: zad2.c
	$(CC) $(CFLAGS) -o zad2 zad2.c $(LDLIBS)

zad3: zad3.c
	$(CC) $(CFLAGS) -o zad3 zad3.c $(LDLIBS)

zad4: zad4.c
	$(CC) $(CFLAGS) -o zad4 zad4.c $(LDLIBS)